import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { MobileNav } from '../widgets/MobileNav'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Used Car Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}
